### Get all airport
GET http://localhost:3000/api/v1/airport

### Get airport by ID
GET http://localhost:3000/api/v1/airport?search=lombok

### Create a new airport
POST http://localhost:3000/api/v1/airport
Content-Type: application/json

# {
#     "airport_id": "LOP",
#     "airport_name": "Lombok Praya International Airport",
#     "continent": "Asia",
#     "country": "Indonesia",
#     "city": "Lombok"
# }

{
    "airport_id": "CGK",
    "airport_name": "Soekarno Hatta International Airport",
    "continent": "Asia",
    "country": "Indonesia",
    "city": "Jakarta"
}

### edit airport berdasarkan airport id
PUT http://localhost:3000/api/v1/airport/YIA
Content-Type: application/json

{
    "airport_name": "Yogyakarta International Airport",
    "continent": "Asia",
    "country": "Indonesia",
    "city": "Yogyakarta"
}

### delete airport berdasarkan airportId
DELETE http://localhost:3000/api/v1/airport/YIA