### Register User
POST http://localhost:3000/api/v1/register
Content-Type: application/json

{
  "name": "ilham",
  "email": "gqgeepo@muatoc.com",
  "no_telp": "082304732146229",
  "password": "password123"
}

### Renew OTP
POST http://localhost:3000/api/v1/renew-otp
Content-Type: application/json

{
  "email": "kqdytn@mynanaimohomes.com"
}

### Verify OTP
POST http://localhost:3000/api/v1/verify-otp
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJlbWFpbCI6ImdxZ2VlcG9AbXVhdG9jLmNvbSIsImlhdCI6MTcxNzQzNjkyMywiZXhwIjoxNzE3NTIzMzIzfQ.jOa2ubrIAWDAL7AoICCf-u_bWQqJOjLk7brATMhEEuI
Content-Type: application/json

{
  "otp": 301888
}

### get all user
GET http://localhost:3000/api/v1/all-user

### Login User with Email
POST http://localhost:3000/api/v1/login
Content-Type: application/json

{
  "emailOrNoTelp": "travelajaaa@gmail.com",
  "password": "DMmey1kA"
}

### auth / login dengan token 
GET  http://localhost:3000/api/v1/auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJlbWFpbCI6ImtxZHl0bkBteW5hbmFpbW9ob21lcy5jb20iLCJpYXQiOjE3MTcwMTQxMjksImV4cCI6MTcxNzEwMDUyOX0.O9MwGPsiM31UNYTnZeIxp2Y5b4cuqidIzGonlivAUac

### Login User with No. Telp
POST http://localhost:3000/api/v1/login
Content-Type: application/json

{
  "emailOrNoTelp": "08217216229",
  "password": "newPassword1234"
}

###
POST http://localhost:3000/api/v1/forgot-password
Content-Type: application/json

{
    "email": "kqdytn@mynanaimohomes.com"
}

###
POST http://localhost:3000/api/v1/reset-password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImtxZHl0bkBteW5hbmFpbW9ob21lcy5jb20iLCJpYXQiOjE3MTcwMTQxOTd9.v47PUU1iUpDkXhoAykf4isXxxct6KazIAxLvQtf2n-c
Content-Type: application/json

{
  "password": "newPassword1234",
  "confirmPassword": "newPassword1234"
}

### GET PROFILE
GET http://localhost:3000/api/v1/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJlbWFpbCI6ImtxZHl0bkBteW5hbmFpbW9ob21lcy5jb20iLCJpYXQiOjE3MTcwMTQyODksImV4cCI6MTcxNzEwMDY4OX0.oT_JteCY2CrLpPShEPxndJoEEatGAa4T0Cg5Dg5jxiU


### UPDATE USER BY ID
POST http://localhost:3000/api/v1/updateprofile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJlbWFpbCI6ImtxZHl0bkBteW5hbmFpbW9ob21lcy5jb20iLCJpYXQiOjE3MTcwMTQyODksImV4cCI6MTcxNzEwMDY4OX0.oT_JteCY2CrLpPShEPxndJoEEatGAa4T0Cg5Dg5jxiU
Content-Type: application/json

{
  "name": "ilham praditya",
  "no_telp": "0976273456700"
}

###
GET http://localhost:3000/api/v1/google