### Register User
POST http://localhost:3000/api/v1/register
Content-Type: application/json

{
  "name": "ilham",
  "email": "nvhofancld@miteon.com",
  "no_telp": "082121629",
  "password": "password123"
}

### Renew OTP
POST http://localhost:3000/api/v1/renew-otp
Content-Type: application/json

{
  "email": "kevinyohanesteen@gmail.com"
}

### Verify OTP
POST http://localhost:3000/api/v1/verify-otp
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJudmhvZmFuY2xkQG1pdGVvbi5jb20iLCJpYXQiOjE3MTY2NjUzMzgsImV4cCI6MTcxNjc1MTczOH0.ECOlYqAw6rz_m__gWIABXi8XbIOweiw-tcghHHoPZNU
Content-Type: application/json

{
  "otp": 927983
}

### get all user
GET http://localhost:3000/api/v1/all-user

### Login User with Email
POST http://localhost:3000/api/v1/login
Content-Type: application/json

{
  "emailOrNoTelp": "21082010211@student.upnjatim.ac.id",
  "password": "password123"
}

### auth / login dengan token 
GET  http://localhost:3000/api/v1/auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiZW1haWwiOiIyMTA4MjAxMDIxMUBzdHVkZW50LnVwbmphdGltLmFjLmlkIiwiaWF0IjoxNzE2NTY0OTczLCJleHAiOjE3MTY2NTEzNzN9.8qpZPVoo-9UuxXPFpqetyXT3D8QcM24vmU0WoJg9imE

### Login User with No. Telp
POST http://localhost:3000/api/v1/login
Content-Type: application/json

{
  "emailOrNoTelp": "08212162176767",
  "password": "password123"
}

###
POST http://localhost:3000/api/v1/forgot-password
Content-Type: application/json

{
    "email": "21082010211@student.upnjatim.ac.id"
}

###
POST http://localhost:3000/api/v1/reset-password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiZW1haWwiOiIyMTA4MjAxMDIxMUBzdHVkZW50LnVwbmphdGltLmFjLmlkIiwiaWF0IjoxNzE2NTY0OTczLCJleHAiOjE3MTY2NTEzNzN9.8qpZPVoo-9UuxXPFpqetyXT3D8QcM24vmU0WoJg9imE
Content-Type: application/json

{
  "password": "newPassword1234",
  "confirmPassword": "newPassword1234"
}

### GET PROFILE
GET http://localhost:3000/api/v1/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiZW1haWwiOiIyMTA4MjAxMDIxMUBzdHVkZW50LnVwbmphdGltLmFjLmlkIiwiaWF0IjoxNzE2NTY0OTczLCJleHAiOjE3MTY2NTEzNzN9.8qpZPVoo-9UuxXPFpqetyXT3D8QcM24vmU0WoJg9imE


### UPDATE USER BY ID
POST http://localhost:3000/api/v1/updateprofile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiZW1haWwiOiIyMTA4MjAxMDIxMUBzdHVkZW50LnVwbmphdGltLmFjLmlkIiwiaWF0IjoxNzE2NTY0OTczLCJleHAiOjE3MTY2NTEzNzN9.8qpZPVoo-9UuxXPFpqetyXT3D8QcM24vmU0WoJg9imE
Content-Type: application/json

{
  "name": "ilham praditya",
  "no_telp": "097627345670",
  "password": "password12345"
}

##### airport #######

### create airport
POST http://localhost:3000/api/v1/airport
Content-Type: application/json

{
    "airportId": "CGK",
    "airport_name": "Soekarno Hatta International Airport",
    "continent": "Asia",
    "country": "Indonesia",
    "city": "Jakarta"
}

### get all airport
GET  http://localhost:3000/api/v1/airport

### search air port berdasarkan nama airport dan juga kota 
GET  http://localhost:3000/api/v1/airport?search=jakarta

### edit airport berdasarkan airport id
PUT http://localhost:3000/api/v1/airport/YIA
Content-Type: application/json

{
    "airport_name": "Yogyakarta International Airport",
    "continent": "Asia",
    "country": "Indonesia",
    "city": "Yogyakarta"
}

### delete airport berdasarkan airportId
DELETE http://localhost:3000/api/v1/airport/YIA