### Register User
POST https://expressjs-develop.up.railway.app/api/v1/register
Content-Type: application/json

{
  "name": "ilham",
  "email": "wtbrwcfijjzkcgb@maxamba.com",
  "no_telp": "0823032198469",
  "password": "password123"
}

### Renew OTP
POST http://localhost:3000/api/v1/renew-otp
Content-Type: application/json

{
  "email": "weywstlmia@nespressopixie.com"
}

### Verify OTP
POST http://localhost:3000/api/v1/verify-otp
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMSwiZW1haWwiOiJibGxrdHRnZUBtaXRlb24uY29tIiwiaWF0IjoxNzE3Njg2ODU1LCJleHAiOjE3MTc3NzMyNTV9.xAWU-V9P5NskJcXxipM59hJ1Mh2DRTJQ3Q4YLk7_O4s
Content-Type: application/json

{
  "otp": 665073
}

### get all user
GET http://localhost:3000/api/v1/all-user

### Login User with Email
POST http://localhost:3000/api/v1/login
Content-Type: application/json

{
  "emailOrNoTelp": "eloxhtops@maxamba.com",
  "password": "password123"
}

### auth / login dengan token 
GET  http://localhost:3000/api/v1/auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJlbWFpbCI6ImtxZHl0bkBteW5hbmFpbW9ob21lcy5jb20iLCJpYXQiOjE3MTcwMTQxMjksImV4cCI6MTcxNzEwMDUyOX0.O9MwGPsiM31UNYTnZeIxp2Y5b4cuqidIzGonlivAUac

### Login User with No. Telp
POST http://localhost:3000/api/v1/login
Content-Type: application/json

{
  "emailOrNoTelp": "08217216229",
  "password": "newPassword1234"
}

###
POST http://localhost:3000/api/v1/forgot-password
Content-Type: application/json

{
    "email": "bllkttge@miteon.com"
}

###
POST http://localhost:3000/api/v1/reset-password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMSwiZW1haWwiOiJibGxrdHRnZUBtaXRlb24uY29tIiwiaWF0IjoxNzE3Njg3MTA4fQ._gAQmd7B1zXf6Yt922s1ztT0pk0ovcvcshsQGOx-xpw
Content-Type: application/json

{
  "password": "newPassword123",
  "confirmPassword": "newPassword123"
}

### GET PROFILE
GET http://localhost:3000/api/v1/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJlbWFpbCI6ImtxZHl0bkBteW5hbmFpbW9ob21lcy5jb20iLCJpYXQiOjE3MTcwMTQyODksImV4cCI6MTcxNzEwMDY4OX0.oT_JteCY2CrLpPShEPxndJoEEatGAa4T0Cg5Dg5jxiU


### UPDATE USER BY ID
POST http://localhost:3000/api/v1/updateprofile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJlbWFpbCI6ImtxZHl0bkBteW5hbmFpbW9ob21lcy5jb20iLCJpYXQiOjE3MTcwMTQyODksImV4cCI6MTcxNzEwMDY4OX0.oT_JteCY2CrLpPShEPxndJoEEatGAa4T0Cg5Dg5jxiU
Content-Type: application/json

{
  "name": "ilham praditya",
  "no_telp": "0976273456700"
}

###
GET http://localhost:3000/api/v1/google