### Get All Flights
GET http://localhost:3000/api/v1/flights

### Get All Flights
GET https://expressjs-develop.up.railway.app/api/v1/flights

### Get Flight By ID
GET http://localhost:3000/api/v1/flights/GA0000002

### Get Flight By ID
GET https://expressjs-develop.up.railway.app/api/v1/flights/GA0000002


### Create Flight
POST http://localhost:3000/api/v1/flights
Content-Type: application/json

{
  "flight_id": "GAECO0000001",
  "price": 1000000.00,
  "date": "2024-06-20",
  "departure_time": "2024-06-20T14:00:00.000Z",
  "arrival_time": "2024-06-20T18:00:00.000Z",
  "airline_id": "JT",
  "arrival_airport_id": "SUB",
  "destination_airport_id": "LOP",
  "promotion_id": 1,
  "seat_class_id": 1
}
### Create Flight
POST https://expressjs-develop.up.railway.app/api/v1/flights
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJlbWFpbCI6InByYWRpdHlhaWxoYW0yNUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MTgzNjE2MjUsImV4cCI6MTcxODQ0ODAyNX0.C7BCxHGq6UUzq5QntEq-7CjYk4DvNtkJfeoWwBuw_fo
Content-Type: application/json

{
  "flight_id": "GABUSS0000005",
  "price": 3000000.00,
  "date": "2024-06-20",
  "departure_time": "2024-06-20T14:00:00.000Z",
  "arrival_time": "2024-06-20T18:00:00.000Z",
  "airline_id": "QG",
  "arrival_airport_id": "SUB",
  "destination_airport_id": "CGK",
  "promotion_id": 1,
  "seat_class_id": 8
}

### Create Flight
POST http://localhost:3000/api/v1/flights
Content-Type: application/json

{
  "flight_id": "GA0000001",
  "price": 1000000.00,
  "date": "2024-06-05",
  "departure_time": "2024-06-05T14:00:00.000Z",
  "arrival_time": "2024-06-05T18:00:00.000Z",
  "airline_id": "GA",
  "arrival_airport_id": "CGK",
  "destination_airport_id": "LOP",
  "seat_class_id": 1
}

### SEARCH FLIGHT
GET http://localhost:3000/api/v1/search?arrival_airport_id=CGK&destination_airport_id=LOP&date=2024-06-05&seat_class_id=1
