### Get All Flights
GET http://localhost:3000/api/v1/flights
Content-Type: application/json

### Get Flight By ID
GET http://localhost:3000/api/v1/flights/GA0000001


### Create Flight
POST http://localhost:3000/api/v1/flights
Content-Type: application/json

{
  "flight_id": "GA0000006",
  "price": 1000000.00,
  "date": "2024-06-05",
  "departure_time": "2024-06-05T14:00:00.000Z",
  "arrival_time": "2024-06-05T18:00:00.000Z",
  "airline_id": "QG",
  "arrival_airport_id": "CGK",
  "destination_airport_id": "LOP",
  "seat_class_id": 1,
  "promotion_id": 1
}

### SEARCH FLIGHT
GET http://localhost:3000/api/v1/search
Content-Type: application/json

{
  "arrival_airport_id": "CGK",
  "destination_airport_id": "LOP",
  "date":"2024-06-05",
  "seat_class_id": 1
}
