### Get
GET http://localhost:3000/api/v1/passenger

### Create passenger
POST http://localhost:3000/api/v1/passenger
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo2LCJlbWFpbCI6ImJ2eHRlam1AbXluYW5haW1vaG9tZXMuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzE4OTA1MjI4LCJleHAiOjE3MTg5OTE2Mjh9.NJ_Q5JsvDrDCfIz1m8xUfUoaMBlnEdYdocTktnG9fhg
Content-Type: application/json

{
  "fullname": "sari",
  "passenger_type": "adult",
  "born_date": "2003-05-15",
  "identity_number": "A124395637893",
  "booking_id": 2
}

### Create passenger
POST https://expressjs-develop.up.railway.app/api/v1/passenger
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJlbWFpbCI6InByYWRpdHlhaWxoYW0yNUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MTgzNjE2MjUsImV4cCI6MTcxODQ0ODAyNX0.C7BCxHGq6UUzq5QntEq-7CjYk4DvNtkJfeoWwBuw_fo
Content-Type: application/json

{
  "fullname": "mullet3",
  "passenger_type": "adult",
  "born_date": "2003-05-15",
  "identity_number": "A12767093",
  "booking_id": 41
}

###
POST http://localhost:3000/api/v1/passenger
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1LCJlbWFpbCI6InR5Ym56ZG5uZGdhQG1heGFtYmEuY29tIiwiaWF0IjoxNzE4MDM3NTU3LCJleHAiOjE3MTgxMjM5NTd9.T8Nkrv-1uahccbp2VNjv6pqU3s-BvSQBuqpDeDK9JDQ
Content-Type: application/json

{
  "fullname": "Rayeang 2",
  "passenger_type": "adult",
  "born_date": "2003-05-15",
  "citizen": "IDN",
  "identity_number": "A1234567893",
  "booking_id": 23
}


### GETBYTOKEN
GET http://localhost:3000/api/v1/passenger-token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo2LCJlbWFpbCI6InVlZG5scXdha29jYXdlQG1heGFtYmEuY29tIiwiaWF0IjoxNzE4MDI5NTQ1LCJleHAiOjE3MTgxMTU5NDV9.HL33Ca4VpIfvrsugf1DIcxtDd_TYwYPsGWlApZtro30
