### Get
GET http://localhost:3000/api/v1/passenger

### Create passenger
POST http://localhost:3000/api/v1/passenger
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMSwiZW1haWwiOiJibGxrdHRnZUBtaXRlb24uY29tIiwiaWF0IjoxNzE3Njg3MTA4fQ._gAQmd7B1zXf6Yt922s1ztT0pk0ovcvcshsQGOx-xpw
Content-Type: application/json

{
  "fullname": "Rayeang 22",
  "passenger_type": "adult",
  "born_date": "2003-05-15",
  "citizen": "IDN",
  "identity_number": "A1234567892",
  "booking_id": 4
}

### GETBYTOKEN
GET http://localhost:3000/api/v1/passenger-token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMSwiZW1haWwiOiJibGxrdHRnZUBtaXRlb24uY29tIiwiaWF0IjoxNzE3Njg3MTA4fQ._gAQmd7B1zXf6Yt922s1ztT0pk0ovcvcshsQGOx-xpw
