### CREATE PAYMENT EWALLET
POST http://localhost:3000/api/v1/payment_wallet
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozLCJlbWFpbCI6InBrcXB4c0BtYXhhbWJhLmNvbSIsImlhdCI6MTcxNzM5NDU4NiwiZXhwIjoxNzE3NDgwOTg2fQ.IzofSsduFE3Rk634cfpKnhRTSFB0I3OSXnujWDy1V5g
Content-Type: application/json

{
    "payment_method": "Dana",
    "no_telp": "089090909090",
    "booking_code": "TVLAJA-000003"
}


### CREATE PAYMENT BANK
POST http://localhost:3000/api/v1/payment_bank
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1LCJlbWFpbCI6IndleXdzdGxtaWFAbmVzcHJlc3NvcGl4aWUuY29tIiwiaWF0IjoxNzE3NDE1NjM1LCJleHAiOjE3MTc1MDIwMzV9.6-dyTsCUB7DFkQ0BOAgiiuh9dms9BYfpEoWTCLZvxCw
Content-Type: application/json

{
    "payment_method": "BRI",
    "card_number": "82748274284287421",
    "valid_until": "12/25",
    "booking_code": "TVLAJA-000004"
}

###
GET http://localhost:3000/api/v1/payment
