GET http://localhost:3000/api/v1/promotion


###
POST http://localhost:3000/api/v1/promotion
Content-Type: application/json

{
  "discount": 20,
  "startDate": "2024-06-01T14:00:00.000Z",
  "endDate": "2024-06-02T14:00:00.000Z"
}
###
POST https://expressjs-develop.up.railway.app/api/v1/promotion
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJlbWFpbCI6InByYWRpdHlhaWxoYW0yNUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MTgzNjE2MjUsImV4cCI6MTcxODQ0ODAyNX0.C7BCxHGq6UUzq5QntEq-7CjYk4DvNtkJfeoWwBuw_fo
Content-Type: application/json

{
  "discount": 30,
  "startDate": "2024-06-01T14:00:00.000Z",
  "endDate": "2024-06-02T14:00:00.000Z"
}

###
### Get All Promotion
GET http://localhost:3000/api/v1/promotion?page=1&limit=4