### CREATE TICKET

POST https://expressjs-develop.up.railway.app/api/v1/create-ticket
Content-Type: application/json

{
    "seat_id": 10,
    "passenger_id": 6
}

### CREATE TICKET

POST http://localhost:3000/api/v1/ticket
Content-Type: application/json

{
    "seat_id": 8,
    "passenger_id": 3
}

### GET TICKET
GET http://localhost:3000/api/v1/ticket/TESTVLAJA-000014
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJlbWFpbCI6InJncnpjanRAbmVzcHJlc3NvcGl4aWUuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3MTkzMzcwNjAsImV4cCI6MTcxOTQyMzQ2MH0.5JiWjMVDsLPsGfCKpms5ZGw8hHOdzG32Dz_NTIwe-ww
### GET TICKET
GET https://expressjs-develop.up.railway.app/api/v1/ticket/TVLAJADOM000006
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo2LCJlbWFpbCI6ImJ2eHRlam1AbXluYW5haW1vaG9tZXMuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzE4OTcyNDg4LCJleHAiOjE3MTkwNTg4ODh9.UEj-SzNBN1BOypTnN_5ryeXq27Y5_YZMKsle72ZFJmI