### Register User
POST http://localhost:3000/api/v1/register
Content-Type: application/json

{
  "name": "user2",
  "email": "pradityailham04@gmail.com",
  "no_telp": "082121",
  "password": "password123"
}

### Renew OTP
POST http://localhost:3000/api/v1/renew-otp
Content-Type: application/json

{
  "email": "xhdpdvzpptyfeu@miteon.com"
}

### Verify OTP
POST http://localhost:3000/api/v1/verify-otp
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJwcmFkaXR5YWlsaGFtMDRAZ21haWwuY29tIiwiaWF0IjoxNzE2NTU1MjEwLCJleHAiOjE3MTY2NDE2MTB9.zaAjC27v1W5mxxiwpTCUsFL9KGleyJ3X5hz5dV2pj-g
Content-Type: application/json

{
  "otp": 157295
}

### get all user
GET http://localhost:3000/api/v1/all-user

### Login User with Email
POST http://localhost:3000/api/v1/login
Content-Type: application/json

{
  "emailOrNoTelp": "pradityailham04@gmail.com",
  "password": "password123"
}

### auth / login dengan token 
GET  http://localhost:3000/api/v1/auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJwcmFkaXR5YWlsaGFtMDRAZ21haWwuY29tIiwiaWF0IjoxNzE2NTU4Mzg3LCJleHAiOjE3MTY2NDQ3ODd9.Uo4_ZxlG8MQpdmYWRavMzJi2BRK3qACEQBbkF9bxUi4

### Login User with No. Telp
POST http://localhost:3000/api/v1/login
Content-Type: application/json

{
  "emailOrNoTelp": "08212162176767",
  "password": "password123"
}

###
POST http://localhost:3000/api/v1/forgot-password
Content-Type: application/json

{
    "email": "fhndkajxqhewe@mynanaimohomes.com"
}

###
POST http://localhost:3000/api/v1/reset-password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImZobmRrYWp4cWhld2VAbXluYW5haW1vaG9tZXMuY29tIiwiaWF0IjoxNzE2NTQ3MjAyfQ.O8exyYT4JfdU8hK9_tjbqXKkvCOtMlS19PR-txLK62E
Content-Type: application/json

{
  "password": "newPassword1234",
  "confirmPassword": "newPassword1234"
}

### GET PROFILE
GET http://localhost:3000/api/v1/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJwcmFkaXR5YWlsaGFtMDRAZ21haWwuY29tIiwiaWF0IjoxNzE2NTU4Mzg3LCJleHAiOjE3MTY2NDQ3ODd9.Uo4_ZxlG8MQpdmYWRavMzJi2BRK3qACEQBbkF9bxUi4


### UPDATE USER BY ID
POST http://localhost:3000/api/v1/updateprofile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJnYW50aW5hbWFAZ21haWwuY29tIiwiaWF0IjoxNzE2NTMzNDc5LCJleHAiOjE3MTY2MTk4Nzl9.Mm8LHzRefvIa_dm4VwjvncZ4dR3DGM54amRqn9LyeBM
Content-Type: application/json

{
  "name": "tes123",
  "no_telp": "0976273227372323",
  "password": "password1234"
}