### Register User
POST http://localhost:3000/api/v1/register
Content-Type: application/json

{
  "name": "user2",
  "email": "pradityailham25@gmail.com",
  "no_telp": "081234567802",
  "password": "password123"
}

### Renew OTP
POST http://localhost:3000/api/v1/renew-otp
Content-Type: application/json

{
  "email": "pradityailham25@gmail.com"
}

### Verify OTP
POST http://localhost:3000/api/v1/verify-otp/633f768280b4e9b37121f1e5c4f12553
Content-Type: application/json

{
  "otp": 102729
}

### get all user
GET http://localhost:3000/api/v1/all-user

### Login User with Email
POST http://localhost:3000/api/v1/login
Content-Type: application/json

{
  "emailOrNoTelp": "pradityailham25@gmail.com",
  "password": "password123"
}

### auth / login dengan token 
GET  http://localhost:3000/api/v1/auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJwcmFkaXR5YWlsaGFtMjVAZ21haWwuY29tIiwiaWF0IjoxNzE2NDkyMDYwLCJleHAiOjE3MTY1Nzg0NjB9.VZFogT1aS8ap_aEjZxOLgfVKsh9Pae1H-t45o5QpGM8

### Login User with No. Telp
POST http://localhost:3000/api/v1/login
Content-Type: application/json

{
  "emailOrNoTelp": "081234567802",
  "password": "password123"
}

###
POST http://localhost:3000/api/v1/forgot-password
Content-Type: application/json

{
    "email": "pradityailham25@gmail.com"
}

###
POST http://localhost:3000/api/v1/reset-password?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InByYWRpdHlhaWxoYW0yNUBnbWFpbC5jb20iLCJpYXQiOjE3MTY0OTMwOTd9.fnVrogn9Dv4IiBPIfEiFKW4P4bH1hzh7p_42OvCeSQU
Content-Type: application/json

{
  "password": "newPassword1234",
  "confirmPassword": "newPassword1234"
}